---
title: "Grouped/Ungrouped Regressions with ln(population) to account for skew"
output: html_notebook
---

```{r}
library("dplyr")
library("MASS")
library(splines)
library(Ecdat)
library(car)
library(lmtest)
library(stargazer)
```


```{r}

#cities <- read.csv('C:/Users/ather/CS Projects/CETLab/caeecc-energy-efficiency/cities_2.csv')
cities <- read.csv("C:/Users/ather/R/CETLAB/cities_demo_joined.csv")
cities_full <- read.csv("C:/Users/ather/R/CETLAB/cities_demo_joined.csv")

demo <- read.csv('C:/Users/ather/R/CETLAB/census_race_combined_by_city.csv')
demoall <- read.csv('C:/Users/ather/R/CETLAB/census_race_group_by_city.csv')

```

```{r}

cities <- na.omit(cities)
#cities_full <- na.omit(cities_full)


row.names(cities) <- NULL

car::Boxplot(cities$Total.Tax.Revenue)

#dropping large outlier cities with LA and SF
cities <- subset(cities, SiteCity != "los angeles")
cities <- subset(cities, SiteCity != "san francisco")
#cities <- subset(cities, SiteCity != "SAN DIEGO")
cities <- subset(cities, SiteCity != "san jose")
#cities <- subset(cities, SiteCity != "OAKLAND")

row.names(cities) <- NULL

car::Boxplot(cities$Total.Tax.Revenue)

summary(cities)
```



```{r}
#create ln_pop variable as ln(total_population)
cities$ln_pop = log(cities$total_population)

#group data by ln_pop
cities_lnq1 <- subset(cities, ln_pop < 9.5)
cities_lnq2 <- subset(cities, ln_pop >= 9.5 & ln_pop < 11.5)
cities_lnq3 <- subset(cities, ln_pop >= 11.5 & ln_pop < 12.5)
cities_lnq4 <- subset(cities, ln_pop > 12.5)

#generate budget per capita
cities$budget_per_cap = cities$Budget / cities$total_population

#generate budget per tax dollar
cities$budget_per_taxrev = cities$Budget / cities$Total.Tax.Revenue

#generate tax revenue per capita
cities$taxrev_per_cap = cities$Total.Tax.Revenue / cities$total_population

```


```{r}
#group information (count, means/ranges, visualization)
count(cities_lnq1)
count(cities_lnq2)
count(cities_lnq3)
count(cities_lnq4)

summary(cities_lnq1$total_population)
summary(cities_lnq2$total_population)
summary(cities_lnq3$total_population)
summary(cities_lnq4$total_population)

hist(cities_lnq1$total_population)
hist(cities_lnq2$total_population)
hist(cities_lnq3$total_population)
hist(cities_lnq4$total_population)
```

```{r}
#checking which variables would be closer to normal with log transform VST
hist(log(cities$Total.Tax.Revenue))
hist(log(cities$total_population))
hist(cities$ces_score_median)
hist(log(cities$median_household_income_usd))
hist(cities$dac_proportion)
hist(cities$ruca_average)
hist(log(cities$Budget))
```

```{r}
#regressions on full cities data with log transform variance stabilizing function


#by recommendation of professor, this model log transforms the outcome variable and not the predictors, this model is made without the final predictor variables in order to compare the difference in significance and R-squared values

reg_model_outcome = lm(log(Budget) ~ Total.Tax.Revenue + total_population + ces_score_median + median_household_income_usd + ruca_average, data = cities)

summary(reg_model_outcome)
plot(reg_model_outcome)
```


```{r}
#testing dropping one of the two colinear variables

taxrev_no_pop = lm(log(Budget) ~ Total.Tax.Revenue + ces_score_median + median_household_income_usd + ruca_average, data = cities)
summary(taxrev_no_pop)

pop_no_taxrev = lm(log(Budget) ~ total_population + ces_score_median + median_household_income_usd + ruca_average, data = cities)
summary(pop_no_taxrev)

#keep taxrevenue, drop population

```

```{r}
#quick note:
#before adding the %'s of budget/resource budget, according to the step AIC we did with prof Tatum,

#this seems to be the best Budget model by AIC before adding %'s of budget
aic_model_budget = lm(log(Budget) ~ median_household_income_usd + Total.Tax.Revenue + ruca_average + ces_score_median, data = cities)
summary(aic_model_budget)
plot(aic_model_budget)
```


```{r}

#AIC based on likelihood,
#even though based on F-test it shows insignificant var, AIC shows that the larger model is significant
#log(budget) ~ income, taxrev, ruca, ces_score, population

#test step AIC to see which variables the step validation picks
aic_model_budget = stepAIC(lm(log(Budget) ~ median_household_income_usd + Total.Tax.Revenue + ruca_average + ces_score_median + dac_proportion + `X..OBF.Budget` + `X..Resource.Budget`, data = cities))

summary(aic_model_budget)
plot(aic_model_budget)

bptest(aic_model_budget)
gqtest(aic_model_budget)

```

```{r}
#running AIC on our different ln population groups:

step_lnq1 = stepAIC(lm(log(Budget) ~ median_household_income_usd + Total.Tax.Revenue + ruca_average + ces_score_median + dac_proportion + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_lnq1))

summary(step_lnq1)
plot(step_lnq1)

step_lnq2 = stepAIC(lm(log(Budget) ~ median_household_income_usd + Total.Tax.Revenue + ruca_average + ces_score_median + dac_proportion + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_lnq2))

summary(step_lnq2)
plot(step_lnq2)

step_lnq3 = stepAIC(lm(log(Budget) ~ median_household_income_usd + Total.Tax.Revenue + ruca_average + ces_score_median + dac_proportion + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_lnq3))

summary(step_lnq3)
plot(step_lnq3)

step_lnq4 = stepAIC(lm(log(Budget) ~ median_household_income_usd + Total.Tax.Revenue + ruca_average + ces_score_median + dac_proportion + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_lnq4))

summary(step_lnq4)
plot(step_lnq4)

```


```{r}

#bunch of t-tests on the split data

quantile(cities$TotalFirstYearGrosskWh, na.rm = TRUE)
bottomq_firstyear = subset(cities, TotalFirstYearGrosskWh <= 22382.8)
topq_firstyear = subset(cities, TotalFirstYearGrosskWh > 22382.8)

quantile(cities$Budget, na.rm = TRUE)
bottomq_budget = subset(cities, Budget <= 1.868783e+04)
topq_budget = subset(cities, Budget > 1.868783e+04)

t.test(bottomq_budget$ruca_average, topq_budget$ruca_average, na.action = na.omit)
t.test(bottomq_firstyear$ruca_average, topq_firstyear$ruca_average, na.action = na.omit)

t.test(bottomq_budget$budget_per_cap, topq_budget$budget_per_cap)
t.test(bottomq_firstyear$budget_per_cap, topq_firstyear$budget_per_cap)

t.test(bottomq_budget$taxrev_per_cap, topq_budget$taxrev_per_cap)
t.test(bottomq_firstyear$taxrev_per_cap, topq_firstyear$taxrev_per_cap)

```

```{r}
#spline regression testing, using the taxrev_no_pop model

spline_model = lm(log(Budget) ~ splines::bs(total_population, knots = c(8746, 24958, 68146)) + Total.Tax.Revenue + ces_score_median + median_household_income_usd + ruca_average, data = cities)

summary(spline_model)

population_lims = range(cities$total_population)
total_population.grid = seq(from=population_lims[1], to=population_lims[2])
pred = predict(spline_model, newdata = list(total_population = total_population.grid), se=T)

```

```{r}
plot(spline)
```

```{r}
#this section of demographic data is of non-white and white proportions, since theyre recorded in separate rows, this reshapes into columns instead
demo_reshape <- reshape(demo, idvar = "city", timevar = "combined_group", direction = "wide")

cities$SiteCity <- tolower(cities$SiteCity)
demo_reshape$city <- tolower(demo_reshape$city)
#join with cities
cities_demos_joined <- left_join(cities, demo_reshape, by = c("SiteCity" = "city"))
```

```{r}
demoall = na.omit(demoall)
#this section of demographic data is of all race groups, similarly to previous chunk, it will need to be reshaped and then included in the AIC regression
demoall_reshape <- reshape(demoall, idvar = "city", timevar = "group",direction = "wide")
write.csv(demoall_reshape, "C:/Users/ather/R/CETLAB/demoall_reshape.csv")

summary(demoall_reshape)

cities$SiteCity <- tolower(cities$SiteCity)
#demoall_reshape$city <- tolower(demo_reshape$city)
#join with cities
cities_demos_joined <- read.csv("C:/Users/ather/R/CETLAB/cities_demo_joined.csv")

print(cities_demos_joined)

```


```{r}
#step AIC including demographics varaibles
cities_demos_model <- stepAIC(lm(log(Budget) ~ median_household_income_usd + Total.Tax.Revenue + ruca_average + ces_score_median + total_population + dac_proportion + `proportion.Non-white` + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_demos_joined))

summary(cities_demos_model)
plot(cities_demos_model)
bptest(cities_demos_model)
gqtest(cities_demos_model)
```

```{r}
#stepaic with demo on kwh
cities_demos_model_kwh <- stepAIC(lm(log(TotalFirstYearGrosskWh+1) ~ median_household_income_usd + Total.Tax.Revenue + ruca_average + ces_score_median + total_population + dac_proportion + `proportion.Non-white` + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_demos_joined))

summary(cities_demos_model_kwh)
plot(cities_demos_model_kwh)
bptest(cities_demos_model_kwh)
gqtest(cities_demos_model_kwh)

```

```{r}
#energy program budget is lower than it should be based on this tax revenue

#underserved being in the bottom quintile for budget per cap and total first year gross per cap

#create groups based on quantiles for budget per capita and first year gross per capita
cities$budget_percap <- cities$Budget/cities$total_population
quantile(cities$budget_percap)
budget_percap_lq <- subset(cities, budget_percap <= 1.703341)
budget_percap_uq <- subset(cities, budget_percap >= 1.003352e+01)


cities$firstyeargross_percap <- cities$TotalFirstYearGrosskWh/cities$total_population
quantile(cities$firstyeargross_percap)
fyg_percap_lq <- subset(cities, firstyeargross_percap <= 1.654831)
fyg_percap_uq <- subset(cities, firstyeargross_percap >= 14.963557)

```
```{r}

#t tests with quintiles split by budget per capita, testing 

t.test(budget_percap_lq$dac_proportion, budget_percap_uq$dac_proportion)
t.test(budget_percap_lq$ces_score_median, budget_percap_uq$ces_score_median)
t.test(budget_percap_lq$median_household_income_usd, budget_percap_uq$median_household_income_usd)
t.test(budget_percap_lq$ruca_average, budget_percap_uq$ruca_average)
t.test(budget_percap_lq$proportion.White.alone, budget_percap_uq$proportion.White.alone)
t.test(budget_percap_lq$proportion.Black.or.African.American.alone, budget_percap_uq$proportion.Black.or.African.American.alone)
t.test(budget_percap_lq$total_population, budget_percap_uq$total_population)
t.test(budget_percap_lq$Total.Tax.Revenue, budget_percap_uq$Total.Tax.Revenue)
t.test(budget_percap_lq$Budget, budget_percap_uq$Budget)


```

```{r}

t.test(fyg_percap_lq$dac_proportion, fyg_percap_uq$dac_proportion)
t.test(fyg_percap_lq$ces_score_median, fyg_percap_uq$ces_score_median)
t.test(fyg_percap_lq$median_household_income_usd, fyg_percap_uq$median_household_income_usd)
t.test(fyg_percap_lq$ruca_average, fyg_percap_uq$ruca_average)
t.test(fyg_percap_lq$proportion.White.alone, fyg_percap_uq$proportion.White.alone)
t.test(fyg_percap_lq$proportion.Black.or.African.American.alone, fyg_percap_uq$proportion.Black.or.African.American.alone)

```



```{r}
full_regression <- lm(log(Budget) ~ dac_proportion + ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget` + proportion.White.alone + proportion.Black.or.African.American.alone + proportion.American.Indian.and.Alaska.Native.alone + proportion.Asian.alone + proportion.Native.Hawaiian.and.Other.Pacific.Islander.alone + proportion.Some.other.race.alone, data = cities)

summary(full_regression)
```


```{r}
#thursday test regressions:
#cities$logbudgetperkwh <- log(cities$Budget)/cities$TotalFirstYearGrosskWh
#cities$logbudgetperkwh[is.infinite(cities$logbudgetperkwh)] <- 0
lnbudget <- lm(log(Budget) ~ dac_proportion + ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities)

lnkwh <- lm(log(TotalFirstYearGrosskWh+1) ~ ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities)

lnbudget_aic <- stepAIC(lm(log(Budget) ~ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities))

lnkWh_aic <- stepAIC(lm(log(TotalFirstYearGrosskWh+1) ~ ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities))

lnbudget_percap <- lm(log(Budget/total_population) ~ ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities)

lnkWh_percap <- lm(log((TotalFirstYearGrosskWh+1)/total_population) ~ ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities)

lnkWh_percap_aic <- stepAIC(lm(log(TotalFirstYearGrosskWh+1/total_population) ~ ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities))

lnbudget_percap_aic <- stepAIC(lm(log(Budget/total_population) ~ ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities))

```

```{r}
#stargazer table:

stargazer(lnbudget_percap, lnkWh_percap, lnkWh_percap_aic, lnbudget_percap_aic, type="text", title = "Regression Table", align = TRUE)
```
```{r}
#stargazer table:

stargazer(lnbudget, lnkwh, lnbudget_aic, lnkWh_aic, type="text", title = "Regression Table", align = TRUE)
```



```{r}
#thursday test regressions:
#cities$logbudgetperkwh <- log(cities$Budget)/cities$TotalFirstYearGrosskWh
#cities$logbudgetperkwh[is.infinite(cities$logbudgetperkwh)] <- 0
lnbudget_full <- lm(log(Budget) ~ dac_proportion + ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_full)

lnkwh_full <- lm(log(TotalFirstYearGrosskWh+1) ~ ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_full)

lnbudget_aic_full <- stepAIC(lm(log(Budget) ~ces_score_median + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_full))

lnkWh_aic_full <- stepAIC(lm(log(TotalFirstYearGrosskWh+1) ~ ces_score_median + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_full))

lnbudget_percap_full <- lm(log(Budget/total_population) ~ ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_full)

lnkWh_percap_full <- lm(log((TotalFirstYearGrosskWh+1)/total_population) ~ ces_score_median + Total.Tax.Revenue + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_full)

lnkWh_percap_aic_full <- stepAIC(lm(log(TotalFirstYearGrosskWh+1/total_population) ~ ces_score_median + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_full))

lnbudget_percap_aic_full <- stepAIC(lm(log(Budget/total_population) ~ ces_score_median + median_household_income_usd + ruca_average + `X..OBF.Budget` + `X..Resource.Budget`, data = cities_full))

```
