---
title: "clean map script"
author: "Austin Covey"
date: "5/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, load packages}
library(sf)
library(data.table)
library(tigris)
library(ggplot2)
library(maps)
library(tmap)
library(USAboundaries)
library(maptools)
library(tidyverse)
library(stringr)
library(viridis)
library(bit64)
library(gridExtra)
library(grid)
library(ggplot2)
library(lattice)
library(GISTools)
```

```{r, load data}
cpuc_file   = 'counties_2.csv'
#df <- fread(cpuc_file) #, colClasses = c('character', df$county_fips))

df <- fread(cpuc_file, header = T, colClasses = c('character', rep(NA, 34)))
# best practice is to classify column as a character as you read the data in.

#rep(NA,11)= NA, NA, NA...... 11 times


# We lack leading zeroes (best practice to have them).
```

```{r, Start Here}

#make a data frame
all_counties<- map_data("county")
# Lot of observations, this stores geometries of county polygons in an inefficient way (there are 3000 counties in US, but way more observations (storing in point, line way))

#visualize
ggplot(data=all_counties)+
  geom_polygon(aes(x = long, y = lat, fill = region, group = group))+ #if you were using a different coord system you would have to change long and lat
  # fill indicates what we want to colored in, in this case we're doing the states (region=state)
  # group is extremely important. There are lots of point values in this data. Group tells R that all of these points belong in a county
  coord_fixed(1.3)+
  guides(fill = FALSE) #if change to fill = any other color, then you would see the outline of all of the counties (county lines are there even when you put FALSE; however we don't see them at this granularity)

```

```{r, subset to CA}
CA_counties<- subset(x = all_counties, subset = region == "california")
# Check subset with: table(CA_counties$region)
```

```{r, make lowercase}
#the county names don't match (our data has capitalized first letters County =/= county), so we have to change it
df_edited <- df
df_edited$County <- str_to_lower(df_edited$County)
head(df_edited) #check to see if the county names did change
```

```{r, merge on count name}
#check dimensions before the merge 
dim(df_edited)
dim(CA_counties)

#merge
merged_data<- left_join(CA_counties, df_edited, by = c("subregion"="County")) #the left_join takes all the unique values from left one and only add the matches from the right (doesn't matter in this case because they WILL match since we checked already)
dim(merged_data) 
```

```{r, visualize mean income}

#Mean Income
t <- ggplot(data = merged_data)+
  geom_polygon(aes(x = long, y = lat, group = group, fill= `Mean Income`))+ #change the fill argument from plot to plot
  coord_fixed(1.3)+
  ggtitle("Mean Household Income by County")+ #change title from plot to plot
  theme_classic()+ #order matters in ggplot
  scale_fill_viridis() +
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text = element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())

#there are ways to change colors and get rid of the axis (read more into ggplot:http://sape.inf.usi.ch/quick-reference/ggplot2/colour)

```

```{r, visualize log pop}

log_pop <- log(merged_data$tot_pop + 1)
merged_data$log_pop <- log(merged_data$tot_pop + 1)

# LOG Population
p <- ggplot(data = merged_data) +
  geom_polygon(aes(x = long, y = lat, group = group, fill= `log_pop`)) + 
  coord_fixed(1.3) +
  ggtitle("County Population (LOG)") +
  theme_classic() +
  scale_fill_viridis() +
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text = element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())
```

```{r, visualize energy savings}
#LOG Energy Savings
log_savings <- log(merged_data$TotalFirstYearGrosskWh + 1)
merged_data$log_savings <- log(merged_data$TotalFirstYearGrosskWh + 1)

ggplot(data = merged_data) +
  geom_polygon(aes(x = long, y = lat, group = group, fill= `log_savings`)) + 
  coord_fixed(1.3) +
  ggtitle("Log Energy Savings by County") + 
  theme_classic() + 
  scale_fill_viridis() +
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text=element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())

#Energy Savings
ggplot(data = merged_data) +
  geom_polygon(aes(x = long, y = lat, group = group, fill= `TotalFirstYearGrosskWh`)) + 
  coord_fixed(1.3) +
  ggtitle("Energy Savings by County") + 
  theme_classic() + 
  scale_fill_viridis() +
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text=element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())

```

```{r, visualize budget}

#LOG Budget
log_budget <- log(merged_data$Budget + 1)
merged_data$log_budget <- log(merged_data$Budget + 1)

ggplot(data = merged_data) +
  geom_polygon(aes(x = long, y = lat, group = group, fill= `log_budget`)) + 
  coord_fixed(1.3) +
  ggtitle("Log Budget by County") + 
  theme_classic() + 
  scale_fill_viridis() +
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text=element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())

#Budget
ggplot(data = merged_data)+
  geom_polygon(aes(x = long, y = lat, group = group, fill= `Budget`))+ 
  coord_fixed(1.3)+
  ggtitle("Budget by County")+ 
  theme_classic()+ 
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text=element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())

```

```{r, visualize IRR}

#IRR
p2 <- ggplot(data = merged_data)+
  geom_polygon(aes(x = long, y = lat, group = group, fill= `IRR`))+ 
  coord_fixed(1.3)+
  ggtitle("Relative Rurality by County")+ 
  theme_classic()+ 
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text=element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())

```

```{r, visualize tax revenue}
#ASK MEAS ABOUT INTERGER64
#LOG Tax Revenue
log_taxrev <- log(merged_data$TotalRevenue + 1)
merged_data$log_taxrev <- log(merged_data$TotalRevenue + 1)

ggplot(data = merged_data)+
  geom_polygon(aes(x = long, y = lat, group = group, fill= `log_taxrev`))+ 
  coord_fixed(1.3)+
  ggtitle("LOG Tax Revenue by County")+ 
  theme_classic()+ 
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text=element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())
#Tax Revenue
ggplot(data = merged_data)+
  geom_polygon(aes(x = long, y = lat, group = group, fill= `TotalRevenue`))+ 
  coord_fixed(1.3)+
  ggtitle("Tax Revenue by County")+ 
  theme_classic()+ 
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text=element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())

```

```{r, visualize CES score}

#CES Score
ggplot(data = merged_data)+
  geom_polygon(aes(x = long, y = lat, group = group, fill= `ces_score_median`))+ 
  coord_fixed(1.3)+
  ggtitle("CES Score Median by County")+ 
  theme_classic()+ 
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text=element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())

```
```{r, visualize DAC Proportion}

#DAC Proportion
r <- ggplot(data = merged_data)+
  geom_polygon(aes(x = long, y = lat, group = group, fill= `dac_proportion`))+ 
  coord_fixed(1.3)+
  ggtitle("DAC Proportion by County")+ 
  theme_classic()+ 
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text=element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())

```

```{r, Grid Arrange}
#arranging the maps from income, log_pop, IRR, and dac_proportion
grid.arrange(t, p, p2, r, ncol=2)

#more information on this and other complex layouts https://cran.r-project.org/web/packages/gridExtra/vignettes/arrangeGrob.html#multiple-pages-output
```
```{r}
u <- xyplot(Budget ~ IRR, data = merged_data)
grid.arrange(u, p2, ncol=2)
```
```{r}
t <- xyplot(TotalFirstYearGrosskWh ~ IRR, data = merged_data)
grid.arrange(t, p2, ncol=2)
```

```{r, change CSV into a spatial object}
zip_codes_shape <- st_read("zipcodes/ZCTA2010.shp")
CA_albs <- st_crs(zip_codes_shape)
CA_counties_as_sf <- st_as_sf(CA_counties,
                            coords = c('long', 'lat'),
                            group=group,
                            crs = 4326) #WGS84datum ESPG code = 4326

CA_counties_as_sf_2 <- st_transform(CA_counties_as_sf, crs = CA_albs)
# CA Albers / NAD83 datum ? ESPG = 4269
# Check that this produced a simple feature
```
```{r}
st_crs(CA_counties_as_sf_2)
str(CA_counties_as_sf_2)
```
```{r}

#DAC Proportion
ggplot()+
  geom_sf(data = CA_counties_as_sf_2)+ 
  ggtitle("DAC Proportion by County")+ 
  theme_classic()+ 
  coord_sf()+
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text=element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())

```
```{r}
polygons <- CA_counties %>%
  st_as_sf(coords = c('long', 'lat')) %>%
  st_set_crs(4326) 
polygons <- polygons %>%
  group_by(group) %>%
  summarise(do_union=FALSE) %>%
  st_cast("POLYGON")
grids <- polygons %>%
  st_make_grid(cellsize = 0.2) %>%
  st_centroid() %>%
  st_sf()
grids %>% st_join(polygons, join = st_within)
plot(polygons)
plot(grids)
```

```{r}
str(polygons)
```

```{r}
centroids <- st_centroid(polygons)
plot(centroids)

#merge
centroids_w_subregion<- left_join(centroids, CA_counties, by = c("group"="group")) #the left_join takes all the unique values from left one and only add the matches from the right (doesn't matter in this case because they WILL match since we checked already)
dim(centroids_w_subregion) 
```

```{r, getting long and lat for centroids}
test <- centroids  %>% 
  mutate(lon = map_dbl(geometry, ~st_centroid(.x)[[1]]),
     lat = map_dbl(geometry, ~st_centroid(.x)[[2]]))
```

```{r}
centroid_transform <- st_transform(test, crs = CA_albs)
```

```{r}
library(ggrepel)
#DAC
ggplot(data = merged_data)+
  geom_polygon(aes(x = long, y = lat, group = group, fill= `dac_proportion`))+ 
  geom_label_repel(data = centroid_transform, aes(x = lon, y = lat, label = group))+
  ggtitle("DAC Proportion by County")+ 
  theme_classic()+ 
  coord_sf()+
  theme(axis.title.x = element_blank(),
                           axis.title.y = element_blank(),
                           axis.text=element_blank(),
                           axis.ticks = element_blank(),
                           panel.grid = element_blank())
```