---
title: "Counties Final Stats"
author: "Public Sector UWG Team"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '~/Documents/Github/caeecc-energy-efficiency/for github/data')
```

```{r, load packages}
library(readr)
library(data.table)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(psych)
library(car)
library(fitdistrplus)
```

```{r}
#read in data for County EE programs 
counties<-read.csv("counties_2.csv")
View(counties)
```

```{r}
#making new datatset with o budget omitted and the outliers omitted
counties_subset <- subset(counties, Budget > 0)
counties_x <- counties_subset[!(counties_subset$County %in% c("LOS ANGELES", "SAN FRANCISCO", "SAN DIEGO", "SANTA CLARA")),]

#looking at data and testing for normality
hist(counties_x$Budget)
counties_x$ln_budget <- log(counties_x$Budget+1)
hist(counties_x$ln_budget)

#making a linear regression to test for normality of residuals
counties_x_lm<-lm(ln_budget~Population+IRR+Mean.Income+ces_score_median, data=counties_x)
res.counties_x<-counties_x_lm$residuals #not normal
qqPlot(counties_x_lm) #not normal
shapiro.test(res.counties_x) #not normal
View(counties_x)
```

```{r}
#use the new dataset to do regression that only uses the counties that have budget and get rid of the outliers
counties_x$budget_per_cap_x = counties_x$Budget / counties_x$Population
counties_x$revenue_per_cap = counties_x$TotalRevenue / counties_x$Population
hist(counties_x$budget_per_cap_x)
counties_x$ln_budget_per_cap_x <- log(counties_x$budget_per_cap_x+1)
counties_percap_x_lm<-lm(ln_budget_per_cap_x~revenue_per_cap+Population+IRR+Mean.Income+dac_proportion+X..OBF.Budget+X..Resource.Budget, data=counties_x)
res.counties_percap_x<-counties_percap_x_lm$residuals
qqPlot(counties_percap_x_lm)
shapiro.test(res.counties_percap_x) 
summary(counties_percap_x_lm)
#just irr is significant 
```

```{r}
stepAIC(lm(ln_budget_per_cap_x ~ Mean.Income + revenue_per_cap + Population+ IRR + ces_score_median + dac_proportion + X..OBF.Budget + X..Resource.Budget, data = counties_x))
```

```{r}
counties_percap_x_lm1<-lm(ln_budget_per_cap_x~Population+IRR + ces_score_median + dac_proportion + X..OBF.Budget, data=counties_x)
summary(counties_percap_x_lm1)
```

```{r}
counties_percap_x_lm2<-lm(ln_budget~TotalRevenue+Population+IRR+Mean.Income+dac_proportion+X..OBF.Budget+X..Resource.Budget, data=counties_x)
res.counties_percap_x2<-counties_percap_x_lm2$residuals
qqPlot(counties_percap_x_lm2)
shapiro.test(res.counties_percap_x2) 
summary(counties_percap_x_lm2)
```

```{r}
#use step aic to see which configuration of models is best
stepAIC(lm(ln_budget ~ Mean.Income + TotalRevenue + Population + IRR + ces_score_median + dac_proportion + X..OBF.Budget + X..Resource.Budget, data = counties_x))
```

```{r}
#regression using the recommended variables from step aic for the new dataset
counties_percap_x_lm3<-lm(ln_budget~IRR, data=counties_x)
res.counties_percap_x3<-counties_percap_x_lm3$residuals
qqPlot(counties_percap_x_lm3)
shapiro.test(res.counties_percap_x3) 
summary(counties_percap_x_lm3)
#pop is significant
```

```{r}
library(stargazer)
stargazer(counties_percap_x_lm, counties_percap_x_lm1, counties_percap_x_lm2, counties_percap_x_lm3, type="text", title="Linear Regression Results Budget Data", align=TRUE, dep.var.labels=c("Log of Budget Per Capita", "Log of Budget"), omit.stat=c("LL","ser","f"), order=c("revenue_per_cap","TotalRevenue", "Population", "Mean.Income", "IRR", "dac_proportion", "ces_score_mean", "X..OBF.Budget", "X..Resource.Budget"), covariate.labels = c("Revenue Per Capita","Total Revenue", "Population", "Mean Income", "IRR", "DAC Proportion", "CES Score", "Percent On-bill Financing", "Precent of Resource Programs"), no.space=TRUE)
```

```{r}
counties_x$kwh_per_cap = counties_x$TotalFirstYearGrosskWh / counties_x$Population
hist(counties_x$kwh_per_cap)
counties_x$ln_kwh_per_cap <- log(counties_x$kwh_per_cap+1)
hist(counties_x$ln_kwh_per_cap)
counties_percapkwh_lm<-lm(ln_kwh_per_cap~Population + revenue_per_cap+IRR+Mean.Income+dac_proportion + X..OBF.Budget + X..Resource.Budget, data=counties_x)
res.counties_percapkwh<-counties_percapkwh_lm$residuals
qqPlot(counties_percapkwh_lm)
shapiro.test(res.counties_percapkwh) 
#data is normal so regular regression can be run

summary(counties_percapkwh_lm)
#irr tax rev ces score and dac are all significant 
```

```{r}
#use step aic to see which configuration of models is best
stepAIC(lm(ln_kwh_per_cap ~ Mean.Income + Population + revenue_per_cap + IRR + ces_score_median + dac_proportion + X..OBF.Budget + X..Resource.Budget, data = counties_x))
```
```{r}
#regression with step aic given variables
counties_percapkwh_lm1<-lm(ln_kwh_per_cap~revenue_per_cap+IRR+ces_score_median+dac_proportion, data=counties_x)
res.counties_percapkwh1<-counties_percapkwh_lm1$residuals
qqPlot(counties_percapkwh_lm1)
shapiro.test(res.counties_percapkwh1) 
#data is normal so regular regression can be run

summary(counties_percapkwh_lm1)
#irr tax rev pop ces score and dac are all significant 
```

```{r}
#use the new data set with only ones that have budget data and no oiutliers to look at regression for energy savings using all the variables and look out normality assumptions
counties_x$ln_kwh <- log(counties_x$TotalFirstYearGrosskWh+1)
counties_percapkwh_lm2<-lm(ln_kwh~TotalRevenue+IRR+Mean.Income+ces_score_median+dac_proportion+X..OBF.Budget+X..Resource.Budget, data=counties_x)
res.counties_percapkwh2<-counties_percapkwh_lm2$residuals
qqPlot(counties_percapkwh_lm2)
shapiro.test(res.counties_percapkwh2) 

summary(counties_percapkwh_lm2)
#irr and ces score significant
```
```{r}
#use step aic to see which configuration of models is best
stepAIC(lm(ln_kwh ~ Population + Mean.Income + TotalRevenue + IRR + ces_score_median + dac_proportion + X..OBF.Budget + X..Resource.Budget, data = counties_x))
```

```{r}
#use the new data set with only ones that have budget data and no oiutliers to look at regression for energy savings using all the variables and look out normality assumptions
counties_percapkwh_lm3<-lm(ln_kwh~Population + ces_score_median + IRR, data=counties_x)
res.counties_percapkwh3<-counties_percapkwh_lm3$residuals
qqPlot(counties_percapkwh_lm3)
shapiro.test(res.counties_percapkwh3) 

summary(counties_percapkwh_lm3)
#irr and ces score significant and population are all significant
```

```{r}
stargazer(counties_percapkwh_lm, counties_percapkwh_lm1, counties_percapkwh_lm2, counties_percapkwh_lm3, type="text", title="Linear Regression Results Energy Savings Data", align=TRUE, dep.var.labels=c("Log of Energy Savings Per Capita", "Log of Energy Savings"), omit.stat=c("LL","ser","f"), order=c("revenue_per_cap","TotalRevenue", "Population", "Mean.Income", "IRR", "dac_proportion", "ces_score_mean", "X..OBF.Budget", "X..Resource.Budget"), covariate.labels = c("Revenue Per Capita","Total Revenue", "Population", "Mean Income", "IRR", "DAC Proportion", "CES Score", "Percent On-bill Financing", "Percent of Resource Programs"), no.space=TRUE)
```

```{r}
#Create quantiles of budget
quantile(counties$budget_per_cap)

#create top and bottom quantile
bottomq_budget = subset(counties, Budget <= 1.528228)
topq_budget = subset(counties, Budget > 7.940744)
```

```{r}
#create quantiles of energy savings
quantile(counties$kwh_per_cap)

#create top and bottom quantile
bottomq_energy = subset(counties, TotalFirstYearGrosskWh <= 1.377546)
topq_energy = subset(counties, TotalFirstYearGrosskWh > 11.231349)
```

```{r}
#t tests to compare means of irr in top and bottom
t.test(bottomq_budget$IRR, topq_budget$IRR, na.action = na.omit) #super sig--> makes sense because only real significance in regression
t.test(bottomq_energy$IRR, topq_energy$IRR, na.action = na.omit, var.equal = TRUE) #significant

#t tests to compare means of budget per capita in top and bottom
t.test(bottomq_energy$budget_per_cap, topq_energy$budget_per_cap) #significant -> this more important cuz shoes relationship between energy and budget

#t tests to compare means of total revenue in top and bottom
t.test(bottomq_budget$TotalRevenue, topq_budget$TotalRevenue) #significant
t.test(bottomq_energy$TotalRevenue, topq_energy$TotalRevenue) #not significant

#t tests to compare means of population in top and bottom
t.test(bottomq_budget$Population, topq_budget$Population) #significant
t.test(bottomq_energy$Population, topq_energy$Population) #not significant, not different 

#t tests to compare means of dac proportion in top and bottom
t.test(bottomq_budget$dac_proportion, topq_budget$dac_proportion, var.equal = TRUE) #not significant--> not significant in regressions
t.test(bottomq_energy$dac_proportion, topq_energy$dac_proportion, var.equal = TRUE) #not significant

#t tests to compare means of ces score median in top and bottom
t.test(bottomq_budget$ces_score_median, topq_budget$ces_score_median, var.equal = TRUE) #not significant --> makes sense because not significant with budget in regression
t.test(bottomq_energy$ces_score_median, topq_energy$ces_score_median) #not significant

#t tests to compare means of mean income in top and bottom
t.test(bottomq_budget$Mean.Income, topq_budget$Mean.Income, var.equal = TRUE) #not sig --> makes sense because not significant in any of the regressions
t.test(bottomq_energy$Mean.Income, topq_energy$Mean.Income, var.equal = TRUE) #not sig --> makes sense because not significant in any of the regressions
```

```{r}
#look at average percentage of certain demographics within top and bottom quantile based on budget per cap
t.test(bottomq_budget$perc_wa_avg,topq_budget$perc_wa_avg)

t.test(bottomq_budget$perc_ba_avg, topq_budget$perc_ba_avg)

t.test(bottomq_budget$perc_aa_avg, topq_budget$perc_aa_avg)

t.test(bottomq_budget$perc_ia_avg, topq_budget$perc_ia_avg)

t.test(bottomq_budget$perc_na_avg, topq_budget$perc_na_avg, var.equal = TRUE)

```

```{r}
#look at average percentage of certain demographics within top and bottom quantile based on kwh per cap
t.test(bottomq_energy$perc_wa_avg, topq_energy$perc_wa_avg)

t.test(bottomq_energy$perc_ba_avg, topq_energy$perc_ba_avg)

t.test(bottomq_energy$perc_aa_avg, topq_energy$perc_aa_avg)

t.test(bottomq_energy$perc_ia_avg, topq_energy$perc_ia_avg)

t.test(bottomq_energy$perc_na_avg, topq_energy$perc_na_avg)
```

```{r}
ggp1<-ggplot(counties_x, aes(x = IRR, y = ln_budget_per_cap_x)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")+ ylab("Log of Budget Per Capita")+ xlab("IRR")

ggp2<-ggplot(counties_x, aes(x = IRR, y = ln_kwh_per_cap)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")+ ylab("Log of Energy Savings Per Capita")+ xlab("IRR")

library(gridExtra)
grid.arrange(ggp1, ggp2, ncol = 2)
```

```{r}
ggp3<-ggplot(counties_x, aes(x = IRR, y = ln_budget)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")+ ylab("Log of Budget")+ xlab("IRR")

ggp4<-ggplot(counties_x, aes(x = IRR, y = ln_kwh)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")+ ylab("Log of Energy Savings")+ xlab("IRR")

library(gridExtra)
grid.arrange(ggp3, ggp4, ncol = 2)
```

```{r}
install.packages("remotes")
remotes::install_github("G-Thomson/gthor")
ggplotRegression(lm(ln_budget ~ IRR, data = counties_x))
```

```{r}
ggplot(counties_x, aes(x = IRR, y = ln_budget_per_cap_x)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")
```

```{r}
ggplot(counties_x, aes(x = IRR, y = ln_kwh)) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red")+ ylab("Log of Energy Savings")+ xlab("IRR")
```

